# Default mechanic configuration for EMTOM
# Enable/disable mechanics and configure their parameters

mechanics:
  - name: inverse_open
    params:
      affected_objects: []  # Empty = all doors affected
      affected_types:
        - door

  - name: remote_switch
    params:
      mappings: null  # null = generate random mappings at runtime
      seed: null

  - name: counting_trigger
    params:
      required_count: 3
      targets: []  # Empty = all buttons
      target_types:
        - button
      show_progress: false
