defaults:
  - /llm@plan_config.llm: llama
  - /instruct@plan_config.instruct: few_shot_decentralized_partial_obs_uncoordinated_spatial

_target_: 'habitat_llm.planner.tom_planner.LLMPlanner'
_recursive_: False
_partial_: True

plan_config:
    replanning_threshold: 25
    planning_mode: "cot"
    constrained_generation: False
    enable_rag: False
    rag_dataset_dir: ""
    rag_data_source_name: ""
    example_type: "react"
    centralized: False
    objects_response: False
    objects_response_include_states: False
