CUDA_VISIBLE_DEVICES=3 python -m habitat_llm.examples.planner_demo --config-name baselines/decentralized_zero_shot_react_summary_nn.yaml \
    instruction="navigate to the bathroom" \
    mode="cli" \
    device="cpu" \
    habitat.environment.max_episode_steps=1500 \
    evaluation.save_video=True \
    llm@evaluation.agents.agent_0.planner.plan_config.llm=openai_chat \
    llm@evaluation.agents.agent_1.planner.plan_config.llm=openai_chat \
    trajectory.save=True \
    'trajectory.save_options=["rgb"]' 
