# Task generation configuration
task_generation:
  task_types:
    - theory_of_mind
    - planning
    - causal_reasoning
    - prediction

  per_trajectory_tasks: 3
  min_surprises_required: 1

  difficulty_distribution:
    easy: 0.3
    medium: 0.5
    hard: 0.2

infinite_sampler:
  mechanics_per_world: 3
  exploration_steps: 50
  world_complexity: medium  # simple, medium, complex
