# Default exploration configuration
exploration:
  max_steps: 100
  agent_ids:
    - agent_0
  log_path: data/trajectories/emtom
  snapshot_frequency: 0  # 0 = no world snapshots, N = every N steps
  stop_on_terminal: true

curiosity:
  type: random  # random, llm, scripted
  temperature: 0.7  # For LLM mode
  seed: null  # For random mode

surprise_detection:
  type: rules  # rules, llm, hybrid
  threshold: 0.5  # Minimum normalized surprise level to report
  require_hypothesis: true
